#!/usr/bin/env bash
#
# make-examples.sh Copyright (C) 2026 Daniel H. Huson
#
# Imports a directory of example files into an application's resources, renaming each
# to <original-name>.dat (required for iOS/GluonFX bundling) and regenerating index.dat.
#
# Usage:
#   ./make-examples.sh <source-dir> <resources-examples-dir>
#
# Example:
#   ./make-examples.sh examples src/main/resources/catrenet/examples
#
# Existing display names in the current index.dat are preserved where the resource
# name is unchanged, so hand-written labels are not lost on re-run.
#

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <source-dir> <resources-examples-dir>" >&2
    exit 1
fi

SRC="$1"
DST="$2"

if [[ ! -d "$SRC" ]]; then
    echo "Source directory not found: $SRC" >&2
    exit 1
fi

mkdir -p "$DST"

OLD_INDEX="$DST/index.dat"
NEW_INDEX="$DST/index.dat.new"

# Preserve any display names already recorded, keyed by resource name.
lookup_label() {
    local resource="$1"
    if [[ -f "$OLD_INDEX" ]]; then
        awk -F'|' -v r="$resource" '
            /^[[:space:]]*#/ {next}
            /^[[:space:]]*$/ {next}
            {
                gsub(/^[ \t]+|[ \t]+$/, "", $1)
                if ($1 == r && NF > 1) {
                    gsub(/^[ \t]+|[ \t]+$/, "", $2)
                    print $2
                    exit
                }
            }' "$OLD_INDEX"
    fi
}

{
    echo "# Generated by make-examples.sh - edit display names freely, they are preserved."
    echo "#"
    echo "#   <resource> [| <display name> [| <real file name>]]"
    echo "#"
    echo "# Every resource ends in .dat for iOS/GluonFX bundling; the real name is the"
    echo "# resource name with that .dat stripped."
    echo
} > "$NEW_INDEX"

count=0
while IFS= read -r -d '' file; do
    name=$(basename "$file")
    [[ "$name" == "index.dat" ]] && continue

    resource="$name.dat"
    cp "$file" "$DST/$resource"

    label=$(lookup_label "$resource")
    if [[ -z "$label" ]]; then
        label="${name%.*}"
    fi

    printf '%-32s | %s\n' "$resource" "$label" >> "$NEW_INDEX"
    count=$((count + 1))
done < <(find "$SRC" -maxdepth 1 -type f ! -name '.*' -print0 | sort -z)

mv "$NEW_INDEX" "$OLD_INDEX"

echo "Imported $count example(s) into $DST"
echo "Index: $OLD_INDEX"
cat "$OLD_INDEX"
